# Generated by Django 5.2.7 on 2025-10-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
